// Copyright Epic Games, Inc. All Rights Reserved.

using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;
using SolidWorks.Interop.swpublished;
using SolidWorksTools;
using SolidWorksTools.File;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Threading;
using DatasmithSolidworks.Names;
using Environment = System.Environment;

namespace DatasmithSolidworks
{
	/**
	 * Main class for the Datasmith Solidworks addin.
	 */ 
	[Guid("6d79a432-9aa3-4457-aefd-ade6f2b17cce"), ComVisible(true)]
	[SwAddin(Description = "Datasmith Solidworks Exporter", Title = "SolidworksDatasmith", LoadAtStartup = true)]
	public class Addin : ISwAddin
	{
		private int AddinID = 0;
		private ICommandManager CommandManager = null;
		private BitmapHandler BmpHandler = new BitmapHandler();
		private Dictionary<int, FDocument> OpenDocuments = new Dictionary<int, FDocument>();

		private UserProgressBar ProgressBar = null;

		private const int MainCmdGroupID = 5;
		private const int MainItemID1 = 0;
		private const int MainItemID2 = 1;

		public ISldWorks SolidworksApp { get; private set; } = null;
		public FDocument CurrentDocument { get; private set; } = null;

		// DebugLog is enabled with DatasmithSolidworksDebugOutput conditional compilation symbol

		class FDebugLog
		{
			private readonly int MainThreadId;
			private ConcurrentQueue<string> MessagesQueue = new ConcurrentQueue<string>();
			private Thread LogWriterThread;
			private int Indentation = 0;

			public FDebugLog(int InMainThreadId)
			{
				MainThreadId = InMainThreadId;
				LogWriterThread = new Thread(() =>
				{
					LogWriterProc();
				});

				LogWriterThread.Start();
			}

			private void LogWriterProc()
			{
				string LogPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
					"UnrealDatasmithExporter/Saved/Logs/UnrealDatasmithSolidworksExporterDebug.log");

				StreamWriter LogFile = new StreamWriter(LogPath);

				while (true)
				{
					while (MessagesQueue.TryDequeue(out string Message))
					{
						LogFile.WriteLine(Message);
					}
					LogFile.Flush();

					Thread.Sleep(10);
				}
			}

			public void LogDebug(string Message)  
			{
				// todo: in general, Solidworks api shouldn't be called from another thread(it's slower) 
				//   so better to identify all those places and fix them
				// Debug.Assert(MainThreadId == Thread.CurrentThread.ManagedThreadId);
				MessagesQueue.Enqueue(new string(' ', Indentation*2)+Message);
			}

			public void LogDebugThread(string Message)  
			{
				MessagesQueue.Enqueue(new string(' ', Indentation*2)+Message);
			}

			public void Dedent()
			{
				Indentation --;
			}

			public void Indent()
			{
				Indentation ++;
			}
		};

		private FDebugLog DebugLog;

		int SwThreadId;  // Main thread of Solidworks

		public static Addin Instance { get; private set; } = null;

		public Addin()
		{
			if (Instance == null)
			{
				Instance = this;
				SwThreadId = Thread.CurrentThread.ManagedThreadId;
				StartLogWriterTread();
			}
		}

		public void LogStatusBarMessage(string InMessage)
		{
			if (ProgressBar == null)
			{
				SolidworksApp.GetUserProgressBar(out ProgressBar);
				ProgressBar.Start(0, 100, "");
			}

			ProgressBar.UpdateTitle(InMessage);
		}

		public int GetDocumentId(ModelDoc2 InDoc)
		{
			return InDoc.GetHashCode();
		}

		public void CloseDocument(int InDocId)
		{
			if (OpenDocuments.ContainsKey(InDocId))
			{
				FDocument Doc = OpenDocuments[InDocId];
				if (CurrentDocument == Doc)
				{
					SwitchToDocument(null);
				}
				Doc.Destroy();
				OpenDocuments.Remove(InDocId);
			}
		}

		public void SyncDocumentsWithApp()
		{
			int NumOpenDocs = SolidworksApp.GetDocumentCount();
			HashSet<int> CurrentOpenDocumentsSet = new HashSet<int>();
			object[] ObjDocuments = (object[])SolidworksApp.GetDocuments();
			for (int Index = 0; Index < NumOpenDocs; Index++)
			{
				if (ObjDocuments[Index] is ModelDoc2 Doc)
				{
					CurrentOpenDocumentsSet.Add(GetDocumentId(Doc));
				}
			}

			foreach (int DocKey in OpenDocuments.Keys)
			{
				if (!CurrentOpenDocumentsSet.Contains(DocKey))
				{
					OpenDocuments.Remove(DocKey);
				}
			}
		}

		private bool bDatasmithFacadeDirectLinkInitialized = false;

		public bool ConnectToSW(object InThisSW, int InCookie)
		{
			SolidworksApp = (ISldWorks)InThisSW;
			AddinID = InCookie;

			CommandManager = SolidworksApp.GetCommandManager(AddinID);

			SolidworksApp.SetAddinCallbackInfo(0, this, AddinID);
			SolidworksApp.AddFileSaveAsItem2(AddinID, "OnExportToFile", "Unreal Datamisth (*.udatasmith)", "udatasmith", (int)swDocumentTypes_e.swDocASSEMBLY);
			SolidworksApp.AddFileSaveAsItem2(AddinID, "OnExportToFile", "Unreal Datamisth (*.udatasmith)", "udatasmith", (int)swDocumentTypes_e.swDocPART);

			InitToolbarCommands();
			AttachEventHandlers();

			FDatasmithFacadeElement.SetCoordinateSystemType(FDatasmithFacadeElement.ECoordinateSystemType.RightHandedZup);

			if (!bDatasmithFacadeDirectLinkInitialized)
			{
				FDatasmithFacadeDirectLink.Init();
				bDatasmithFacadeDirectLinkInitialized = true;
			}

			FMaterial.InitializeMaterialTypes();

			OnActiveDocChange();

			return true;
		}

		public bool DisconnectFromSW()
		{
			// Disabled Shutdown as Initing again crashes if the plugin is re-enabled in SW
			// FDatasmithFacadeDirectLink.Shutdown it is required to have plugin dll unloaded but Solidworks doesn't unload the plugin assembly when plugin is disabled
			// So, something like this doesn't work:
			// if (bDatasmithFacadeDirectLinkInitialized)
			// {
			// 	FDatasmithFacadeDirectLink.Shutdown();
			// 	bDatasmithFacadeDirectLinkInitialized = false;
			// }
			// At least make sure to close current connection
			CurrentDocument?.MakeActive(false);

			DetachEventHandlers();
			DestroyToolbarCommands();

			SolidworksApp.RemoveFileSaveAsItem2(AddinID, "OnExportToFile", "Unreal (*.udatasmith)", "udatasmith", (int)swDocumentTypes_e.swDocASSEMBLY);
			SolidworksApp.RemoveFileSaveAsItem2(AddinID, "OnExportToFile", "Unreal (*.udatasmith)", "udatasmith", (int)swDocumentTypes_e.swDocPART);

			Marshal.ReleaseComObject(CommandManager);
			CommandManager = null;

			Marshal.ReleaseComObject(SolidworksApp);
			SolidworksApp = null;

			// The addin _must_ call GC.Collect() here in order to retrieve all managed code pointers
			GC.Collect();
			GC.WaitForPendingFinalizers();

			return true;
		}

		void InitToolbarCommands()
		{
			string Title = "Datasmith";
			string ToolTip = "Unreal Datasmith Exporter for Solidworks";

			// Get the ID information stored in the registry
			object RegistryIDs;
			bool bGetDataResult = CommandManager.GetGroupDataFromRegistry(MainCmdGroupID, out RegistryIDs);

			int[] KnownIDs = new int[2] { MainItemID1, MainItemID2 };
			bool bIgnorePrevious = false;

			if (bGetDataResult)
			{
				if (!KnownIDs.SequenceEqual((int[])RegistryIDs)) // If the IDs don't match, reset the commandGroup
				{
					bIgnorePrevious = true;
				}
			}

			Assembly ThisAssembly = System.Reflection.Assembly.GetAssembly(this.GetType());

			int CmdGroupErr = 0;
			ICommandGroup CmdGroup = CommandManager.CreateCommandGroup2(MainCmdGroupID, Title, ToolTip, "", -1, bIgnorePrevious, ref CmdGroupErr);
			CmdGroup.LargeIconList = BmpHandler.CreateFileFromResourceBitmap("SolidworksDatasmith.ToolbarLarge.bmp", ThisAssembly);
			CmdGroup.SmallIconList = BmpHandler.CreateFileFromResourceBitmap("SolidworksDatasmith.ToolbarSmall.bmp", ThisAssembly);
			CmdGroup.LargeMainIcon = BmpHandler.CreateFileFromResourceBitmap("SolidworksDatasmith.MainIconLarge.bmp", ThisAssembly);
			CmdGroup.SmallMainIcon = BmpHandler.CreateFileFromResourceBitmap("SolidworksDatasmith.MainIconSmall.bmp", ThisAssembly);

			int MenuToolbarOption = (int)(swCommandItemType_e.swMenuItem | swCommandItemType_e.swToolbarItem);
			int CmdIndex0 = CmdGroup.AddCommandItem2("Direct Link Synchronize", 0, "Update the Direct Link connection", "Synchronize", 0, "OnDirectLinkSync", "OnDirectLinkSyncStatus", MainItemID1, MenuToolbarOption);
			int CmdIndex1 = CmdGroup.AddCommandItem2("Pause/Resume DirectLink Auto Sync", 1, "Pause/Resume DirectLink Auto Sync", "Toggle Auto Sync", 1, "OnEnableDisableAutoSync", "OnEnableDisableAutoSyncStatus", MainItemID1, MenuToolbarOption);

			CmdGroup.HasToolbar = true;
			CmdGroup.Activate();

			int[] SupportedDocTypes = new int[]
			{
				(int)swDocumentTypes_e.swDocASSEMBLY,
				(int)swDocumentTypes_e.swDocDRAWING,
				(int)swDocumentTypes_e.swDocPART
			};

			foreach (int DocType in SupportedDocTypes)
			{
				CommandTab CmdTab = CommandManager.GetCommandTab(DocType, Title);

				// If tab exists, but we have ignored the registry info (or changed command group ID), re-create the tab.  Otherwise the ids won't matchup and the tab will be blank
				if (CmdTab != null & !bGetDataResult | bIgnorePrevious)
				{
					CommandManager.RemoveCommandTab(CmdTab);
					CmdTab = null;
				}

				// If CmdTab is null, must be first load (possibly after reset), add the commands to the tabs
				if (CmdTab == null)
				{
					CmdTab = CommandManager.AddCommandTab(DocType, Title);

					CommandTabBox CmdBox = CmdTab.AddCommandTabBox();

					int[] CmdIDs = new int[3];
					int[] TextType = new int[3];

					CmdIDs[0] = CmdGroup.get_CommandID(CmdIndex0);
					CmdIDs[1] = CmdGroup.get_CommandID(CmdIndex1);

					TextType[0] = (int)swCommandTabButtonTextDisplay_e.swCommandTabButton_TextBelow;
					TextType[1] = (int)swCommandTabButtonTextDisplay_e.swCommandTabButton_TextBelow;

					CmdBox.AddCommands(CmdIDs, TextType);
				}
			}
		}

		void DestroyToolbarCommands()
		{
			CommandManager.RemoveCommandGroup(MainCmdGroupID);
		}

		void AttachEventHandlers()
		{
			try
			{
				SldWorks AppEvents = (SldWorks)SolidworksApp;
				AppEvents.ActiveDocChangeNotify += new DSldWorksEvents_ActiveDocChangeNotifyEventHandler(OnActiveDocChange);
				AppEvents.DocumentLoadNotify2 += new DSldWorksEvents_DocumentLoadNotify2EventHandler(OnDocLoad);
				AppEvents.FileNewNotify2 += new DSldWorksEvents_FileNewNotify2EventHandler(OnFileNew);
				AppEvents.FileCloseNotify += new DSldWorksEvents_FileCloseNotifyEventHandler(OnFileClose);
				AppEvents.CommandCloseNotify += new DSldWorksEvents_CommandCloseNotifyEventHandler(OnCommandClose);
				AppEvents.OnIdleNotify += new DSldWorksEvents_OnIdleNotifyEventHandler(OnIdle);
			}
			catch {}
		}

		void DetachEventHandlers()
		{
			try
			{
				SldWorks AppEvents = (SldWorks)SolidworksApp;
				AppEvents.ActiveDocChangeNotify -= new DSldWorksEvents_ActiveDocChangeNotifyEventHandler(OnActiveDocChange);
				AppEvents.DocumentLoadNotify2 -= new DSldWorksEvents_DocumentLoadNotify2EventHandler(OnDocLoad);
				AppEvents.FileNewNotify2 -= new DSldWorksEvents_FileNewNotify2EventHandler(OnFileNew);
				AppEvents.FileCloseNotify -= new DSldWorksEvents_FileCloseNotifyEventHandler(OnFileClose);
				AppEvents.CommandCloseNotify -= new DSldWorksEvents_CommandCloseNotifyEventHandler(OnCommandClose);
				AppEvents.OnIdleNotify -= new DSldWorksEvents_OnIdleNotifyEventHandler(OnIdle);
			}
			catch {}
		}

		void SwitchToDocument(ModelDoc2 InDoc)
		{
			CurrentDocument?.MakeActive(false);
			CurrentDocument = null;

			if (InDoc == null)
			{
				return;
			}

			int DocId = GetDocumentId(InDoc);

			// the units setup seems to only influence the display of measurements
			// the vertices returned by solidworks are based on metres
			// because unreal is based on centimetres, we simply need to multiply distances by 100

			//GeometryScale = 100f;

			/*
			int units = doc.Extension.GetUserPreferenceInteger((int)swUserPreferenceIntegerValue_e.swUnitsLinear, (int)swUserPreferenceOption_e.swDetailingNoOptionSpecified);
			if (units == (int)swLengthUnit_e.swANGSTROM) GeometryScale = 1f/100000000f;
			else if (units == (int)swLengthUnit_e.swCM) GeometryScale = 1f;
			else if (units == (int)swLengthUnit_e.swFEET) GeometryScale = 30.48f;
			else if (units == (int)swLengthUnit_e.swFEETINCHES) GeometryScale = 1f;
			else if (units == (int)swLengthUnit_e.swINCHES) GeometryScale = 2.54f;
			else if (units == (int)swLengthUnit_e.swMETER) GeometryScale = 100f;
			else if (units == (int)swLengthUnit_e.swMICRON) GeometryScale = 1f/10000f;
			else if (units == (int)swLengthUnit_e.swMIL) GeometryScale = 160934.4f;
			else if (units == (int)swLengthUnit_e.swMM) GeometryScale = 1f/10f;
			else if (units == (int)swLengthUnit_e.swNANOMETER) GeometryScale = 1f/10000000f;
			else if (units == (int)swLengthUnit_e.swUIN) GeometryScale = 0.00000254f;
			*/

			if (OpenDocuments.ContainsKey(DocId))
			{
				CurrentDocument = OpenDocuments[DocId];
			}
			else
			{
				switch (InDoc.GetType())
				{
					case (int)swDocumentTypes_e.swDocPART: CurrentDocument = new FPartDocument(DocId, InDoc as PartDoc, null, null, new FComponentName()); break;
					case (int)swDocumentTypes_e.swDocASSEMBLY: CurrentDocument = new FAssemblyDocument(DocId, InDoc as AssemblyDoc, null); break;
					default: throw new Exception("Unsupported document type");
				}

				OpenDocuments.Add(DocId, CurrentDocument);
			}

			CurrentDocument.MakeActive(true);
		}

		#region UI Callbacks

		public void OnDirectLinkSync()
		{
			CurrentDocument?.OnDirectLinkSync();
		}

		public int OnDirectLinkSyncStatus()
		{
			return CurrentDocument != null ? 1 : 0;
		}

		public void OnEnableDisableAutoSync()
		{
			if (CurrentDocument != null)
			{
				CurrentDocument.ToggleDirectLinkAutoSync();
			}
		}

		public int OnEnableDisableAutoSyncStatus()
		{
			// 0 Deselects and disables the item
			// 1 Deselects and enables the item; this is the default state if no update function is specified
			// 2 Selects and disables the item
			// 3 Selects and enables the item

			if (CurrentDocument == null)
			{
				return 0;
			}

			return CurrentDocument.bDirectLinkAutoSync ? 3 : 1;
		}

		#endregion

		#region SolidWorks Registration

		[ComRegisterFunctionAttribute]
		public static void RegisterFunction(Type InType)
		{
			SwAddinAttribute SWattr = null;
			Type Type = typeof(Addin);

			foreach (System.Attribute Attr in Type.GetCustomAttributes(false))
			{
				if (Attr is SwAddinAttribute)
				{
					SWattr = Attr as SwAddinAttribute;
					break;
				}
			}

			try
			{
				Microsoft.Win32.RegistryKey HKLM = Microsoft.Win32.Registry.LocalMachine;
				Microsoft.Win32.RegistryKey HKCU = Microsoft.Win32.Registry.CurrentUser;

				string KeyName = "SOFTWARE\\SolidWorks\\Addins\\{" + InType.GUID.ToString() + "}";
				Microsoft.Win32.RegistryKey AddinKey = HKLM.CreateSubKey(KeyName);
				AddinKey.SetValue(null, 0);
				AddinKey.SetValue("Description", SWattr.Description);
				AddinKey.SetValue("Title", SWattr.Title);

				KeyName = "Software\\SolidWorks\\AddInsStartup\\{" + InType.GUID.ToString() + "}";
				AddinKey = HKCU.CreateSubKey(KeyName);
				AddinKey.SetValue(null, Convert.ToInt32(SWattr.LoadAtStartup), Microsoft.Win32.RegistryValueKind.DWord);
			}
			catch (System.NullReferenceException E)
			{
				Console.WriteLine("There was a problem registering this dll: SWattr is null. \n\"" + E.Message + "\"");
				System.Windows.Forms.MessageBox.Show("There was a problem registering this dll: SWattr is null.\n\"" + E.Message + "\"");
			}
			catch (System.Exception E)
			{
				Console.WriteLine(E.Message);
				System.Windows.Forms.MessageBox.Show("There was a problem registering the function: \n\"" + E.Message + "\"");
			}
		}

		[ComUnregisterFunctionAttribute]
		public static void UnregisterFunction(Type InType)
		{
			try
			{
				Microsoft.Win32.RegistryKey HKLM = Microsoft.Win32.Registry.LocalMachine;
				Microsoft.Win32.RegistryKey HKCU = Microsoft.Win32.Registry.CurrentUser;

				string KeyName = "SOFTWARE\\SolidWorks\\Addins\\{" + InType.GUID.ToString() + "}";
				HKLM.DeleteSubKey(KeyName);

				KeyName = "Software\\SolidWorks\\AddInsStartup\\{" + InType.GUID.ToString() + "}";
				HKCU.DeleteSubKey(KeyName);
			}
			catch (System.NullReferenceException E)
			{
				Console.WriteLine("There was a problem unregistering this dll: " + E.Message);
				System.Windows.Forms.MessageBox.Show("There was a problem unregistering this dll: \n\"" + E.Message + "\"");
			}
			catch (System.Exception E)
			{
				Console.WriteLine("There was a problem unregistering this dll: " + E.Message);
				System.Windows.Forms.MessageBox.Show("There was a problem unregistering this dll: \n\"" + E.Message + "\"");
			}
		}

		#endregion

		#region Even Handlers

		public void OnExportToFile(string InFileName)
		{
			// Set the extension for which to look
			string Ext = "udatasmith";
			string DotExt = "." + Ext;

			// Strip the trailing 'w' or 'r' and any leading and trailing white space
			InFileName = (InFileName.Substring(0, InFileName.Length - 1)).Trim(' ');

			// Strip extension from the back
			InFileName = (InFileName.Substring(0, InFileName.Length - Ext.Length)).Trim(' ');

			// Change to lowercase to make search case-insensitive
			string SearchString = InFileName.ToLower();

			int NumExtensionOccurrences = 0;
			int Start = 1;
			int NumNonRealExtensions = 0;
			int Pos = 0;

			do
			{
				Pos = SearchString.IndexOf(DotExt.ToLower(), Start - 1) + 1;
				if (Pos > 0)
				{
					NumExtensionOccurrences = NumExtensionOccurrences + 1;

					// Move start point of search
					Start = (int)(Pos + DotExt.Length);

				}

			} while (Pos > 0);

			// There is 1 real extension and n*2 non-real extension
			NumNonRealExtensions = (NumExtensionOccurrences / 2);

			// Start searching from the end to locate the real extension
			// Skip the number of non-real extensions, before reaching the real extension

			// Change to lowercase to make search case-insensitive
			SearchString = InFileName.ToLower();

			Pos = SearchString.LastIndexOf(DotExt.ToLower(), Start);

			InFileName = InFileName.Substring(0, Pos) + DotExt;

			CurrentDocument?.OnExportToFile(InFileName);
		}

		private int OnActiveDocChange()
		{
			ModelDoc2 Current = SolidworksApp.ActiveDoc as ModelDoc2;
			SwitchToDocument(Current);
			return 0;
		}

		private int OnDocLoad(string InDocTitle, string InDocPath)
		{
			ModelDoc2 LoadedModelDoc = SolidworksApp.IGetOpenDocumentByName2(InDocPath);
			ModelDoc2 ActiveModelDoc = SolidworksApp.ActiveDoc as ModelDoc2;

			if (ActiveModelDoc == null || ActiveModelDoc == LoadedModelDoc)
			{
				// Top level document open
				SwitchToDocument(LoadedModelDoc);
			}

			return 0;
		}

		public int OnFileNew(object InNewDoc, int InDocType, string InTemplateName)
		{
			ModelDoc2 Current = SolidworksApp.ActiveDoc as ModelDoc2;
			SwitchToDocument(Current);
			return 0;
		}

		private int OnFileClose(string InFileName, int InReason)
		{
			SyncDocumentsWithApp();
			return 0;
		}

		private int OnCommandClose(int InCommand, int InReason)
		{
			if (InCommand == 2789) // unable to find swCommands_e.swCommands_FileClose enum value in interop enums
			{
				SyncDocumentsWithApp();
			}
			return 0;
		}

		private int OnIdle()
		{
			CurrentDocument?.OnIdle();
			return 0;
		}

		#endregion

		#region Logging

		[Conditional("DatasmithSolidworksDebugOutput")]
		private void StartLogWriterTread()
		{
			DebugLog = new FDebugLog(SwThreadId);
		}

		[Conditional("DatasmithSolidworksDebugOutput")]
		public void LogDebug(string Message)  
		{
			DebugLog.LogDebug(Message);
		}

		[Conditional("DatasmithSolidworksDebugOutput")]
		public void LogDebugThread(string Message)  
		{
			DebugLog.LogDebugThread(Message);
		}

		[Conditional("DatasmithSolidworksDebugOutput")]
		public void LogIndent()  
		{
			DebugLog.Indent();
		}

		[Conditional("DatasmithSolidworksDebugOutput")]
		public void LogDedent()  
		{
			DebugLog.Dedent();
		}

		#endregion
	}
}
